# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:    
  
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [8]
        
    env:
      SNF4J_SKIP_TEST_LOGGING: true
      TRAVIS: true
      
    steps:
    - name: Check out code    
      uses: actions/checkout@v2
      
    - name: Set up Java ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: 'adopt'
        
    - name: Install dependencies
      run: |
        mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    
    - name: Build on Java ${{ matrix.java }}
      run: |
        mvn -B test || echo "Build failed"
        cat snf4j-core/target/surefire-reports/*.txt
        cat snf4j-core-slf4j/target/surefire-reports/*.txt
        
    - name: Upload coverage report
      if: matrix.java == 8
      run: |
        mvn cobertura:cobertura || echo "Code coverage failed"
        bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
