# 
# CI build that assembles artifacts and runs tests for the SNF4J-QUIC project.
#
# USAGE:
# - to skip CI add [skip ci] to the commit message
#
name: QUIC

on:
  pull_request:
    branches: [ quic ]

jobs:
  build:    
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"

    strategy:
      matrix:
        java: [8]
        
    env:
      SNF4J_SKIP_TEST_LOGGING: true
      SNF4J_UNIX_TEST: true
      
    steps:
    - name: Check out code    
      uses: actions/checkout@v4
      
    - name: Install packages
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libsctp-dev
        version: 1.0
          
    - name: Set up Java ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        
    - name: Install dependencies
      run: |
        mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    
    - name: Build on Java ${{ matrix.java }}
      run: |
        mvn -B test
        
    - name: Log failure reports
      if: ${{ failure() }}
      run: |
        cat snf4j-core/target/surefire-reports/*.txt
        cat snf4j-core-log4j2/target/surefire-reports/*.txt
        cat snf4j-core-slf4j/target/surefire-reports/*.txt
        cat snf4j-sctp/target/surefire-reports/*.txt
        cat snf4j-websocket/target/surefire-reports/*.txt
        cat snf4j-tls/target/surefire-reports/*.txt
        cat snf4j-quic/target/surefire-reports/*.txt
    
    - name: Upload coverage to Codecov
      if: matrix.java == 8
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        name: codecov-umbrella
        fail_ci_if_error: true
        verbose: false
